version: '3'
services:
  gin:
    container_name: gin
    build:
      context: ./go-gin
      dockerfile: Dockerfile
    volumes:
      - ./go-gin:/app
    ports:
      - "8080:8080"
#    environment:
#      - GIN_MODE=release
