version: '3'
services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
      - /opt/www/runtime
    ports:
      - "9501:9501"
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
#      - APP_ENV=prod
#      - SCAN_CACHEABLE=true
      - JWT_SECRET=my-secret-key111
      - JWT_ISSUER=test.local

  gserver:
    container_name: gserver
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - "9503:9503"
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


networks:
  default:
    name: hyperf-skeleton
